from pathlib import Path

readme = Path("README.md")
validation = Path("docs/VALIDATION.md")

r = readme.read_text(encoding="utf-8")

old = """## Validation

Run the CPU-vs-ROCm validation workflow:

```bash
./scripts/run_validation.sh
```"""

new = """## Validation

Recommended full local check:

```bash
./scripts/check_rocm_port.sh

This runs both ROCm port hygiene checks and CPU-vs-ROCm smoke validation.

You can also run the CTest entries generated by CMake:

ctest --test-dir build-rocm-plc --output-on-failure

Run only the CPU-vs-ROCm validation workflow:

./scripts/run_validation.sh
```"""

if old in r:
    r = r.replace(old, new)
else:
    print("README validation block not found; skipped exact block replacement")

replacements = {
    "* Rewrite user-facing logs to use ROCm/HIP wording instead of legacy CUDA wording.":
        "* Keep user-facing ROCm/HIP wording clean as the validation matrix grows.",
    "* Replace visible `CudaPrepare`, `Cuda device`, and `cuSparse` labels with ROCm/HIP labels.":
        "* Maintain CTest-backed smoke validation and ROCm hygiene checks.",
    "* Add CPU-vs-ROCm validation scripts.":
        "* Extend validation beyond the current smoke and extended Netlib cases.",
    "* Add a validation result table.":
        "* Add more documented validation result snapshots.",
}

for old_line, new_line in replacements.items():
    r = r.replace(old_line, new_line)

readme.write_text(r, encoding="utf-8")

v = validation.read_text(encoding="utf-8")

ctest_section = """\n## CTest integration

The ROCm port checks are also registered with CTest when the project is configured with `BUILD_TESTING=ON`.

Example:

```bash
ctest --test-dir build-rocm-plc --output-on-failure

Current registered tests:

Test	Purpose	Expected result
rocm_port_hygiene	Checks ROCm/HIP naming and compatibility guardrails	PASS
rocm_smoke_validation	Runs CPU-vs-ROCm smoke validation	PASS

CTest is the recommended standard entry point after configuring a ROCm build tree.
"""

if "## CTest integration" not in v:
    v = v.rstrip() + "\n" + ctest_section + "\n"

validation.write_text(v, encoding="utf-8")

print("updated README.md and docs/VALIDATION.md")
