#!/usr/bin/env python3
"""
Analyze ROCm/HIP copy-related trace data from rocprofv3 CSV output.

This script is intentionally schema-tolerant. It works with the CSV files
generated by current cuPDLP-C-ROCm profiling runs, especially when
rocprofv3 does not emit a separate memory_copy_trace.csv file.

Example:

  python3 scripts/analyze_rocm_copy_trace.py \
    --input profiling/results/manual_memcopy_trace/sc50b_rocprofv3
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple


COPY_API_NAMES = {
    "hipMemcpy",
    "hipMemcpyAsync",
    "hipMemcpyWithStream",
    "hipMemcpyDtoH",
    "hipMemcpyHtoD",
    "hipMemcpyDtoD",
    "hipMemcpy2D",
    "hipMemcpy2DAsync",
    "hipMemcpy3D",
    "hipMemcpy3DAsync",
    "hipMemset",
    "hipMemsetAsync",
}


def clean(value: object) -> str:
    if value is None:
        return ""
    return str(value).strip().strip('"').strip("'")


def read_csv_rows(path: Path) -> Tuple[List[str], List[Dict[str, str]]]:
    with path.open("r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f)
        fields = [clean(x) for x in (reader.fieldnames or [])]
        return fields, list(reader)


def pick(row: Dict[str, str], candidates: Iterable[str]) -> str:
    lower = {clean(k).lower(): clean(v) for k, v in row.items()}
    for key in candidates:
        value = lower.get(key.lower(), "")
        if value:
            return value
    return ""


def pick_float(row: Dict[str, str], candidates: Iterable[str]) -> Optional[float]:
    value = pick(row, candidates)
    if not value:
        return None
    try:
        return float(value.replace(",", ""))
    except ValueError:
        return None


def duration_ns(row: Dict[str, str]) -> Optional[float]:
    value = pick_float(row, [
        "DurationNs", "Duration_ns", "Duration (ns)", "Duration", "duration",
        "End_Timestamp", "End", "end_timestamp", "end",
    ])

    # If there is an explicit duration column, use it.
    for key in row:
        k = clean(key).lower()
        if "duration" in k:
            parsed = pick_float(row, [key])
            if parsed is not None:
                if "ms" in k:
                    return parsed * 1_000_000.0
                if "us" in k or "µs" in k:
                    return parsed * 1_000.0
                return parsed

    start = pick_float(row, ["Start_Timestamp", "Start", "start_timestamp", "start", "Begin", "begin"])
    end = pick_float(row, ["End_Timestamp", "End", "end_timestamp", "end", "Stop", "stop"])
    if start is not None and end is not None and end >= start:
        return end - start
    return None


def name_of(row: Dict[str, str]) -> str:
    return pick(row, ["Name", "name", "Function", "function", "Operation", "operation", "Kernel_Name", "kernel_name"])


def start_ns(row: Dict[str, str]) -> Optional[float]:
    return pick_float(row, ["Start_Timestamp", "Start", "start_timestamp", "start", "Begin", "begin"])


def end_ns(row: Dict[str, str]) -> Optional[float]:
    return pick_float(row, ["End_Timestamp", "End", "end_timestamp", "end", "Stop", "stop"])


def summarize_rows(rows: List[Dict[str, str]], names: Optional[set[str]] = None) -> Dict[str, Dict[str, float]]:
    stats: Dict[str, Dict[str, float]] = defaultdict(lambda: {"count": 0, "total_ns": 0.0, "max_ns": 0.0})
    for row in rows:
        name = name_of(row)
        if not name:
            continue
        if names is not None and name not in names:
            continue
        dur = duration_ns(row)
        if dur is None:
            continue
        stats[name]["count"] += 1
        stats[name]["total_ns"] += dur
        stats[name]["max_ns"] = max(stats[name]["max_ns"], dur)
    return stats


def print_stats(title: str, stats: Dict[str, Dict[str, float]], limit: int = 30) -> None:
    print(f"\n## {title}")
    print("| Name | Count | Total ms | Avg us | Max us |")
    print("|---|---:|---:|---:|---:|")
    for name, s in sorted(stats.items(), key=lambda kv: kv[1]["total_ns"], reverse=True)[:limit]:
        count = int(s["count"])
        total_ns = s["total_ns"]
        avg_us = total_ns / count / 1000.0 if count else 0.0
        print(f"| `{name}` | {count} | {total_ns/1_000_000.0:.3f} | {avg_us:.3f} | {s['max_ns']/1000.0:.3f} |")


def find_files(root: Path) -> Tuple[List[Path], List[Path], List[Path]]:
    hip = sorted(root.glob("*hip_api_trace.csv"))
    kernel = sorted(root.glob("*kernel_trace.csv"))
    memcopy = sorted(root.glob("*memory_copy*.csv"))
    return hip, kernel, memcopy


def print_columns(paths: List[Path]) -> None:
    for path in paths:
        fields, _ = read_csv_rows(path)
        print(f"- `{path.name}` columns: {', '.join(fields)}")


def correlate_copybuffer(root: Path, window_ns: float) -> None:
    hip_paths, kernel_paths, _ = find_files(root)
    if not hip_paths or not kernel_paths:
        return

    _, hip_rows = read_csv_rows(hip_paths[0])
    _, kernel_rows = read_csv_rows(kernel_paths[0])

    memcpy_events = []
    for row in hip_rows:
        name = name_of(row)
        if name in {"hipMemcpy", "hipMemcpyAsync"}:
            s = start_ns(row)
            e = end_ns(row)
            if s is not None and e is not None:
                memcpy_events.append((s, e, name))

    copybuf_events = []
    for row in kernel_rows:
        name = name_of(row)
        if "__amd_rocclr_copyBuffer" in name:
            s = start_ns(row)
            e = end_ns(row)
            if s is not None and e is not None:
                copybuf_events.append((s, e, name))

    matched = 0
    for ks, ke, _ in copybuf_events:
        for hs, he, _ in memcpy_events:
            if abs(ks - hs) <= window_ns or (hs <= ks <= he + window_ns):
                matched += 1
                break

    print("\n## CopyBuffer correlation")
    print(f"- hipMemcpy / hipMemcpyAsync events: {len(memcpy_events)}")
    print(f"- __amd_rocclr_copyBuffer dispatches: {len(copybuf_events)}")
    print(f"- copyBuffer dispatches near HIP memcpy events within {window_ns:.0f} ns: {matched}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="rocprofv3 output directory")
    parser.add_argument("--window-ns", type=float, default=250_000.0, help="Correlation window in ns")
    args = parser.parse_args()

    root = Path(args.input)
    if not root.exists():
        raise SystemExit(f"input directory not found: {root}")

    hip_paths, kernel_paths, memcopy_paths = find_files(root)

    print(f"# ROCm copy trace analysis for `{root}`\n")
    print("## Files")
    print(f"- HIP API trace files: {len(hip_paths)}")
    print(f"- Kernel trace files: {len(kernel_paths)}")
    print(f"- Memory copy trace files: {len(memcopy_paths)}")
    print_columns(hip_paths + kernel_paths + memcopy_paths)

    if hip_paths:
        _, hip_rows = read_csv_rows(hip_paths[0])
        print_stats("HIP memcpy API summary", summarize_rows(hip_rows, {"hipMemcpy", "hipMemcpyAsync", "hipMemset", "hipMemsetAsync"}))

    if kernel_paths:
        _, kernel_rows = read_csv_rows(kernel_paths[0])
        copybuffer_stats = defaultdict(lambda: {"count": 0, "total_ns": 0.0, "max_ns": 0.0})
        for row in kernel_rows:
            name = name_of(row)
            if "__amd_rocclr_copyBuffer" in name or "__amd_rocclr_fillBuffer" in name:
                dur = duration_ns(row)
                if dur is None:
                    continue
                key = "__amd_rocclr_copyBuffer" if "copyBuffer" in name else "__amd_rocclr_fillBuffer"
                copybuffer_stats[key]["count"] += 1
                copybuffer_stats[key]["total_ns"] += dur
                copybuffer_stats[key]["max_ns"] = max(copybuffer_stats[key]["max_ns"], dur)
        print_stats("ROCclr copy/fill buffer kernel summary", copybuffer_stats)

    if memcopy_paths:
        _, rows = read_csv_rows(memcopy_paths[0])
        print_stats("Memory copy trace summary", summarize_rows(rows))
    else:
        print("\n## Memory copy trace")
        print("No separate memory_copy_trace CSV was found. Use HIP API trace and copyBuffer kernel trace as fallback.")

    correlate_copybuffer(root, args.window_ns)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
